# Some kind of deploy
name: Deploy

# Controls when the action will run. 
on:
  push:
    branches: [ sandbox, production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: vars
      - name: Extract short sha
        shell: bash
        run: echo "##[set-output name=sha_short;]$(echo $(git rev-parse --short HEAD))"
        id: vars
      - name: accept bastion key
        run: |
          ssh-keyscan ${{ secrets.BASTION_IP }} >> ~/.ssh/known_hosts
      # Runs the "deploy" command
      - name: Deploy air quotes
        run: |
          ssh circleci@${{ secrets.BASTION_IP }} "echo \"Hello world, deployed tag ${{ steps.vars.outputs.sha_short }} to ${{ steps.vars.outputs.branch }}!\""
