# Some kind of deploy
name: Deploy

# Controls when the action will run. 
on:
  push:
    branches: [ sandbox, production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: accept bastion key
        run: |
          ssh-keyscan ${{ secrets.BASTION_IP }} >> ~/.ssh/known_hosts
      - name: Extract some variables
        shell: bash
        run: | 
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: vars
      - name: Get latest tag
        run: |
          scp circleci@${{ secrets.BASTION_IP }}:/home/circleci/latest_build /home/runner/latest_build
          cat /home/runner/latest_build
      # Runs the "deploy" command
      - name: Deploy air quotes
        run: |
          ssh circleci@${{ secrets.BASTION_IP }} "TAG=$(cat /home/runner/latest_build) && echo \"Hello world, deployed tag $TAG to ${{ steps.vars.outputs.branch }}!\""
